### ISSUE TITLE
Calculate differential splicing 

### ISSUE THREAD

**Issue by SSaleem94** [COMBINE-lab/salmon#859]
Hi , 

I am having issues with calculating the differential splicing using SUPPA.  I have tried several times but kept getting the same error message, even though all files required are uploaded. 

The error message is below:
```
Traceback (most recent call last):
  File "/mnt/storage/nobackup/b7070855/april2023/SUPPA/suppa.py", line 10, in <module>
    import psiPerGene as psiPerIsoform
  File "/mnt/storage/nobackup/b7070855/april2023/SUPPA/psiPerGene.py", line 13, in <module>
    from lib.tools import *
ModuleNotFoundError: No module named 'lib.tools'
[1] "Parsing samples..."
[1] "Loading ./results/iso_tpm_formatted.txt..."
Error: first_condition %in% colnames(input_file) are not all TRUE
Execution halted
[1] "Parsing samples..."
[1] "Loading ./results/events.psi..."
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file './results/events.psi': No such file or directory
Execution halted
Traceback (most recent call last):
  File "/mnt/storage/nobackup/b7070855/april2023/SUPPA/suppa.py", line 10, in <module>
    import psiPerGene as psiPerIsoform
  File "/mnt/storage/nobackup/b7070855/april2023/SUPPA/psiPerGene.py", line 13, in <module>
    from lib.tools import *
ModuleNotFoundError: No module named 'lib.tools'
CalculateDifferentialSplicingEvents.sh: line 24: -e: command not found
```

Could you please help me with this 
**Thank you in advance

**Comment by rob-p** [comment]
Hi @SSaleem94,

  This is an issue upstream in the `SUPPA` tool (or the way that it is installed).  This is not an issue with `salmon`.  I would recommend posting this issue to the `SUPPA` GitHub repository.

Best,
Rob
